/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.music.portlet.model.impl;

import com.liferay.music.portlet.model.Bend;
import com.liferay.music.portlet.model.BendModel;
import com.liferay.music.portlet.model.BendSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Bend service. Represents a row in the &quot;Music_Bend&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.music.portlet.model.BendModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BendImpl}.
 * </p>
 *
 * @author Matea Pjanic
 * @see BendImpl
 * @see com.liferay.music.portlet.model.Bend
 * @see com.liferay.music.portlet.model.BendModel
 * @generated
 */
@JSON(strict = true)
public class BendModelImpl extends BaseModelImpl<Bend> implements BendModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bend model instance should use the {@link com.liferay.music.portlet.model.Bend} interface instead.
	 */
	public static final String TABLE_NAME = "Music_Bend";
	public static final Object[][] TABLE_COLUMNS = {
			{ "bendId", Types.BIGINT },
			{ "name", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table Music_Bend (bendId LONG not null primary key,name VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table Music_Bend";
	public static final String ORDER_BY_JPQL = " ORDER BY bend.bendId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Music_Bend.bendId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.music.portlet.model.Bend"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.music.portlet.model.Bend"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.music.portlet.model.Bend"),
			true);
	public static long NAME_COLUMN_BITMASK = 1L;
	public static long BENDID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Bend toModel(BendSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Bend model = new BendImpl();

		model.setBendId(soapModel.getBendId());
		model.setName(soapModel.getName());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Bend> toModels(BendSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Bend> models = new ArrayList<Bend>(soapModels.length);

		for (BendSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.liferay.music.portlet.model.Bend"));

	public BendModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _bendId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setBendId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _bendId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Bend.class;
	}

	@Override
	public String getModelClassName() {
		return Bend.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("bendId", getBendId());
		attributes.put("name", getName());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long bendId = (Long)attributes.get("bendId");

		if (bendId != null) {
			setBendId(bendId);
		}

		String name = (String)attributes.get("name");

		if (name != null) {
			setName(name);
		}
	}

	@JSON
	@Override
	public long getBendId() {
		return _bendId;
	}

	@Override
	public void setBendId(long bendId) {
		_bendId = bendId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return StringPool.BLANK;
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Bend.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Bend toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Bend)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BendImpl bendImpl = new BendImpl();

		bendImpl.setBendId(getBendId());
		bendImpl.setName(getName());

		bendImpl.resetOriginalValues();

		return bendImpl;
	}

	@Override
	public int compareTo(Bend bend) {
		long primaryKey = bend.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Bend)) {
			return false;
		}

		Bend bend = (Bend)obj;

		long primaryKey = bend.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		BendModelImpl bendModelImpl = this;

		bendModelImpl._originalName = bendModelImpl._name;

		bendModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Bend> toCacheModel() {
		BendCacheModel bendCacheModel = new BendCacheModel();

		bendCacheModel.bendId = getBendId();

		bendCacheModel.name = getName();

		String name = bendCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			bendCacheModel.name = null;
		}

		return bendCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{bendId=");
		sb.append(getBendId());
		sb.append(", name=");
		sb.append(getName());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.liferay.music.portlet.model.Bend");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>bendId</column-name><column-value><![CDATA[");
		sb.append(getBendId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>name</column-name><column-value><![CDATA[");
		sb.append(getName());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Bend.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { Bend.class };
	private long _bendId;
	private String _name;
	private String _originalName;
	private long _columnBitmask;
	private Bend _escapedModel;
}