/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.music.portlet.model.impl;

import com.liferay.music.portlet.model.Bend;
import com.liferay.music.portlet.service.BendLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Bend service. Represents a row in the &quot;Music_Bend&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BendImpl}.
 * </p>
 *
 * @author Matea Pjanic
 * @see BendImpl
 * @see com.liferay.music.portlet.model.Bend
 * @generated
 */
public abstract class BendBaseImpl extends BendModelImpl implements Bend {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bend model instance should use the {@link Bend} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			BendLocalServiceUtil.addBend(this);
		}
		else {
			BendLocalServiceUtil.updateBend(this);
		}
	}
}