/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.music.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Bend service. Represents a row in the &quot;Music_Bend&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.music.portlet.model.impl.BendModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.music.portlet.model.impl.BendImpl}.
 * </p>
 *
 * @author Matea Pjanic
 * @see Bend
 * @see com.liferay.music.portlet.model.impl.BendImpl
 * @see com.liferay.music.portlet.model.impl.BendModelImpl
 * @generated
 */
public interface BendModel extends BaseModel<Bend> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bend model instance should use the {@link Bend} interface instead.
	 */

	/**
	 * Returns the primary key of this bend.
	 *
	 * @return the primary key of this bend
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bend.
	 *
	 * @param primaryKey the primary key of this bend
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the bend ID of this bend.
	 *
	 * @return the bend ID of this bend
	 */
	public long getBendId();

	/**
	 * Sets the bend ID of this bend.
	 *
	 * @param bendId the bend ID of this bend
	 */
	public void setBendId(long bendId);

	/**
	 * Returns the name of this bend.
	 *
	 * @return the name of this bend
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this bend.
	 *
	 * @param name the name of this bend
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.music.portlet.model.Bend bend);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.music.portlet.model.Bend> toCacheModel();

	@Override
	public com.liferay.music.portlet.model.Bend toEscapedModel();

	@Override
	public com.liferay.music.portlet.model.Bend toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}