/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.music.portlet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Song service. Represents a row in the &quot;Music_Song&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.music.portlet.model.impl.SongModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.music.portlet.model.impl.SongImpl}.
 * </p>
 *
 * @author Matea Pjanic
 * @see Song
 * @see com.liferay.music.portlet.model.impl.SongImpl
 * @see com.liferay.music.portlet.model.impl.SongModelImpl
 * @generated
 */
public interface SongModel extends BaseModel<Song> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a song model instance should use the {@link Song} interface instead.
	 */

	/**
	 * Returns the primary key of this song.
	 *
	 * @return the primary key of this song
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this song.
	 *
	 * @param primaryKey the primary key of this song
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the song ID of this song.
	 *
	 * @return the song ID of this song
	 */
	public long getSongId();

	/**
	 * Sets the song ID of this song.
	 *
	 * @param songId the song ID of this song
	 */
	public void setSongId(long songId);

	/**
	 * Returns the album ID of this song.
	 *
	 * @return the album ID of this song
	 */
	public long getAlbumId();

	/**
	 * Sets the album ID of this song.
	 *
	 * @param albumId the album ID of this song
	 */
	public void setAlbumId(long albumId);

	/**
	 * Returns the name of this song.
	 *
	 * @return the name of this song
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this song.
	 *
	 * @param name the name of this song
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.music.portlet.model.Song song);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.music.portlet.model.Song> toCacheModel();

	@Override
	public com.liferay.music.portlet.model.Song toEscapedModel();

	@Override
	public com.liferay.music.portlet.model.Song toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}